// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkwaaghzkncxovgsnpkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrd2FhZ2h6a25jeG92Z3NucGtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzA4MTMsImV4cCI6MjA2MzA0NjgxM30.1R5CCM9PuJoFSUpohgQyS7PWjOdNW8b92d3J9i08tRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);